[project]
name = 'Blockchain-Based-Adaptive-Learning-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.content-verification]
path = 'contracts/content-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.student-identity]
path = 'contracts/student-identity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
